# ServiceAccount 定义
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app: {{ .Release.Name }}-controller
    {{- include "aegisnet.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: {{ .Release.Name }}-agent
    {{- include "aegisnet.labels" . | nindent 4 }}
---
# 控制器 ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app: {{ .Release.Name }}-controller
    {{- include "aegisnet.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # 核心 API 组
  resources: ["pods", "services", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["aegisnet.io"] # 自定义资源 API 组
  resources: ["zerotrustpolicies", "networkidentities"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["aegisnet.io"]
  resources: ["zerotrustpolicies/status", "networkidentities/status"]
  verbs: ["get", "update", "patch"]
---
# 控制器 ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app: {{ .Release.Name }}-controller
    {{- include "aegisnet.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-controller
  apiGroup: rbac.authorization.k8s.io
---
# Agent ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: {{ .Release.Name }}-agent
    {{- include "aegisnet.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # 核心 API 组
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["aegisnet.io"]
  resources: ["zerotrustpolicies"]
  verbs: ["get", "list", "watch"]
---
# Agent ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: {{ .Release.Name }}-agent
    {{- include "aegisnet.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-agent
  apiGroup: rbac.authorization.k8s.io